### ISSUE TITLE
not work in Firefox

### ISSUE THREAD

**Issue by ngnhat** [zyzo/react-dnd-mouse-backend#6]

**Comment by Pumpuli** [comment]
I'm not sure what OP means, but I'm facing an issue on Firefox. I'm using the mouse backend because HTML5 backend doesn't work inside SVG. While this library _does_ work, it also selects text at the same time and that causes flickering among other things.

I tried adding `event.preventDefault()` to the `mousedown` handler [here](https://github.com/zyzo/react-dnd-mouse-backend/blob/f1ba1aacb9c991ea62cb133726d7c5d82a71a0c6/src/MouseBackend.js#L127-L129) (it gets `event` as the second argument), and it seemed to work fine for me. I even had a click handler on the same element and that also worked after the change. Of course I don't know if it breaks some other edge case, I just quickly tested it with FF and Chrome.
